dist: xenial
language: python
python:
  - "3.5"
  - "3.6"

# command to install dependencies
install:
  - pip install codecov
  - pip install pytest pytest-cov
  - pip install -r requirements.txt

# command to run tests
script: 
  - python -m pytest --cov=./

# Push the results back to codecov
after_success:
  - codecov